env:
  NODE_ENV: prod
  INTERNAL_SEARCH_BACKEND_URL: http://contentlab-search-web-app:80
  INTERNAL_CHAT_BACKEND_URL: http://contentlab-chat-web-app:80
  
envSecrets:
  NEXT_PUBLIC_SEARCH_BACKEND_URL: content-lab-ui
  NEXT_PUBLIC_CHAT_BACKEND_URL: content-lab-ui
  NODE_ENV: content-lab-ui

serviceAccount:
  enabled: true
  irsa:
    accountId: "275662791714"
    roleName: "kanopy-prod-cicd-irsa"